pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Use Windows command to build the project
                bat 'mvn clean package'
            }
        }
        stage('Unit Test') {
            steps {
                // Use Windows command to run tests
                bat 'mvn test'
            }
        }
        stage('Archive Results') {
            steps {
                // Archive test results
                junit '**/target/surefire-reports/*.xml'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build and Unit Tests succeeded!'
        }
        failure {
            echo 'Build or Unit Tests failed!'
        }
    }
}
