pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Navigate to the directory containing pom.xml
                dir('user-management/user-management') {
                    bat 'mvn clean package'
                }
            }
        }
        stage('Unit Test') {
            steps {
                // Navigate to the directory containing pom.xml
                dir('user-management/user-management') {
                    bat 'mvn test'
                }
            }
        }
        stage('Archive Results') {
            steps {
                // Navigate to the directory containing test reports
                dir('user-management/user-management') {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build and Unit Tests succeeded!'
        }
        failure {
            echo 'Build or Unit Tests failed!'
        }
    }
}
